apiVersion: v1
kind: Service
metadata:
    name: "aks3jv3af01-319a"
    labels:
        app: "aks3jv3af01-319a"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "aks3jv3af01-319a"